messages:
  prefix: "§e[§cAd§fve§cnt§fCa§cle§fnd§car§e]§r"
  no-permission: "%prefix% §cYou do not have permission to use this command"
  new-reward: "%prefix% §eYou can get a new reward by typing §c/cal"
  reload: "%prefix% §eThe config has been reloaded"
  player-not-found: "%prefix% §cPlayer not found"
  changed-day: "%prefix% §eYou have changed the day to §c%type%"
  give-reward: "%prefix% §eYou give a reward to §c%player%"
  give-reward-other: "%prefix% §eYou have been given a reward by §c%player%"

gui:
  title: "Advent Calendar"
  items:
    sapling:
      material: OAK_SAPLING
      amount: 1
      data: 0
      name: "&6CHRISTMAS"
      lore:
        - "Merry Christmas !"
    book:
      material: BOOK
      amount: 1
      data: 0
      name: "&bInformation"
      lore:
        - "Information number 1"
        - "Information number 2"
    get:
      material: PLAYER_HEAD
      amount: 1
      data: 3
      name: "&6\u27b2  &a%DATE% &2&l\u2714"
      lore:
        - "Line 1"
        - "Line 2"
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDMxMmNhNDYzMmRlZjVmZmFmMmViMGQ5ZDdjYzdiNTVhNTBjNGUzOTIwZDkwMzcyYWFiMTQwNzgxZjVkZmJjNCJ9fX0="
    miss:
      material: PLAYER_HEAD
      amount: 1
      data: 3
      name: "&6\u27b2 &a%DATE% &2&l\u2716"
      lore:
        - "Line 1"
        - "Line 2"
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmY5ZDlkZTYyZWNhZTliNzk4NTU1ZmQyM2U4Y2EzNWUyNjA1MjkxOTM5YzE4NjJmZTc5MDY2Njk4Yzk1MDhhNyJ9fX0="
    waiting:
      material: PLAYER_HEAD
      amount: 1
      data: 3
      name: "&6\u27b2 &a%DATE% &2&l..."
      lore:
        - "Line 1"
        - "Line 2"
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODVhMzc1NWE2ZmUwMTlhMTczY2UzYTQzMDcwNDUyZTc2Nzc2OGQ1NzU1OWQwNGI3M2UyMWI5MDNlYWExYmQ4MiJ9fX0="
    success:
      material: PLAYER_HEAD
      amount: 1
      data: 3
      name: "&6\u27b2 &aReward already collected"
      lore:
        - "Line 1"
        - "Line 2"
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjVhM2I0OWJlZWMzYWIyM2FlMGI2MGRhYjU2ZTljYzhmYTE2NzY5YTI1ODMwYjVkOGQ2YzQ2Mzc4ZjU0NDMwIn19fQ=="

rewards:
  "1":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "2":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "3" :
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "4":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "5":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "6":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "7":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "8":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "9":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "10":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "11":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "12":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "13":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "14":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "15":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "16":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "17":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "18":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "19":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "20":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "21":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "22":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "23":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "24":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
  "25":
    messages:
      - "%prefix% Line 1"
      - "%prefix% Line 2"
    commands:
      - "Command 1"
      - "Command 2"
